// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy-m5AHBLbrM7Si2ZbnN0adUlm3VeZneM',
    appId: '1:630110267110:android:6d4fcf35da34cd94a1fd27',
    messagingSenderId: '630110267110',
    projectId: 'minhhien-solutions',
    databaseURL: 'https://minhhien-solutions.firebaseio.com',
    storageBucket: 'minhhien-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqgIB6I0e61D1eJDD7vG54zisOg_rr-hQ',
    appId: '1:630110267110:ios:b788fd84c6acf562a1fd27',
    messagingSenderId: '630110267110',
    projectId: 'minhhien-solutions',
    databaseURL: 'https://minhhien-solutions.firebaseio.com',
    storageBucket: 'minhhien-solutions.appspot.com',
    iosClientId: '630110267110-a1ofbf8vd2s6u3j4k0e14nhq28krlpua.apps.googleusercontent.com',
    iosBundleId: 'com.happyhomehaiphong.bds',
  );
}
