import 'package:flutter/material.dart';
import 'package:nb_utils/nb_utils.dart';

const rf_primaryColor = Color(0xffd2277f);
const rf_green = Color(0xFF379237);
const rf_splashBgColor = Color(0xFF4064c3);
const rf_categoryBgColor = Color(0xFFF3F3F3);
const rf_selectedCategoryBgColor = Color(0xFFE8ECF7);
const rf_faqBgColor = Color(0xFFD5DDF2);
const rf_notificationBgColor = Color(0xFFF2F2F2);
const rf_rattingBgColor = Color(0xFF2DD35c);
const rf_textColor = Color(0xFF4F4F4F);
const t7textColorSecondary = Color(0xFF9D9D9D);
const t7view_color = Color(0xFFDADADA);
const learner_textColorSecondary = Color(0xFF778390);
// Dark Theme Colors
const appBackgroundColorDark = Color(0xFF121212);
const cardBackgroundBlackDark = Color(0xFF1F1F1F);
const color_primary_black = Color(0xFF131d25);
const appColorPrimaryDarkLight = Color(0xFFF9FAFF);
const iconColorPrimaryDark = Color(0xFF212121);
const iconColorSecondaryDark = Color(0xFFA8ABAD);
const appShadowColorDark = Color(0x1A3E3942);
const appColorPrimary = Color(0xFF1157FA);
const appSecondaryBackgroundColor = Color(0xff343434);
const iconColorPrimary = Color(0xFFFFFFFF);
const iconColorSecondary = Color(0xFFA8ABAD);
const appColorPrimaryLight = Color(0xFFF9FAFF);
const appTextColorPrimary = Color(0xFF212121);
const appTextColorSecondary = Color(0xFF5A5C5E);
const appShadowColor = Color(0x95E9EBF0);
const editTextBgColor = Color(0xFFF8F8F8);
const t1_view_color = Color(0XFFDADADA);
